version: 0.2
phases:
  pre_build:
    commands:
      - ./node_modules/.bin/cypress install --force
  build:
    commands:
      - npx cypress run -record --browser chrome

  post_build:
    commands:

