version: 0.2
phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - npx cypress cache path
      - /root/ .cache/Cypress
      - npx cypress run --config https://thechachaproject.com/
